GET {{url}}/doctors/populate
Accept: application/json
###


GET {{url}}/doctors
Accept: application/json
###

GET {{url}}/doctors/4
Accept: application/json
###

GET {{url}}/doctors/specialty/SURGERY
Accept: application/json
###

GET {{url}}/doctors/birthdate/range?from=1981-01-01&to=1985-01-01
Accept: application/json
###

POST {{url}}/doctors
Content-Type: application/json
Accept: application/json

{
    "name": "Dr. Namjoon Kim",
    "dateOfBirth": "1994-09-12",
    "yearOfGraduation": 2018,
    "nameOfClinic": "Map of the Soul Clinic",
    "specialty": "PSYCHIATRY"
}
###

PUT {{url}}/doctors/4
Content-Type: application/json
Accept: application/json

{
    "dateOfBirth": "1996-01-16",
    "yearOfGraduation": 2019,
    "nameOfClinic": "Black Veins Pink Blood Clinic",
    "specialty": "GERIATRICS"
}
###


### Exception Handling
GET {{url}}/doctors/100

###

GET {{url}}/doctors/specialty/INVALID_SPECIALTY

###

GET {{url}}/doctors/birthdate/range?from=1981-01-01&to=198-01-01